name: Build Flutter APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # هذه الخطوة ستمسح أي ملفات أندرويد قديمة وتنشئ ملفات حديثة تدعم الـ v2 embedding
      - name: Recreate Flutter Android Structure
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.castbrowser.app

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      # خطوة رفع الملف ليظهر لك في الأسفل للتحميل
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
